spring:
  cloud:
    gateway:
      routes:
      - id: ejemplo
        uri: http://localhost:8080
        predicates:
        - Path=/api/ejemplo/**
        filters:
        - StripPrefix=2
      - id: ms-usuarios
        uri: http://localhost:8888
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
